Repository acm-ucr/h4b-website, pull requests merged in 2024-07, with the labels that each got.

#25 Title component
  src/components/Title.jsx
Labels: Ready to Review, Quin

#30 Jefren/implement picture
  src/components/Picture.jsx
Labels: Ready to Review, Sean

#26 Implemented board member card
  src/app/board/page.js
  src/components/board/Board.jsx
Labels: Fix Changes, Sean, Board

#39 Haokun yang123/additional info
  src/components/involvement/AdditionalInfo.jsx
Labels: Ready to Review, Sean, Involvement

#24 Place Holder Website / Styling
  package-lock.json
  src/components/Button.jsx
  tailwind.config.js
Labels: Help, Quin

#40 Qhgill/involve
  src/components/Button.jsx
  src/components/Title.jsx
  src/components/home/Involve.jsx
  src/components/involvement/AdditionalInfo.jsx
Labels: Home

#42 Implement UpcomingCard.jsx
  src/components/home/Upcoming.jsx
  src/components/home/UpcomingCard.jsx
Labels: Ready to Review, Fix Changes, Sean

#38 Footer
  src/app/layout.js
  src/components/Footer.jsx
Labels: Ready to Review, Sean

#45 made Item.jsx
  src/components/Item.jsx
Labels: Ready to Review, Involvement

#48 Mapping for footer socials
  src/components/Footer.jsx
  src/components/Navigation.jsx
  src/components/home/Upcoming.jsx
  src/data/Footer.js
  src/data/navItems.js
Labels: Fix Changes, Sean

#47 Ale00111/implement connect
  src/app/support/page.js
  src/components/support/Connect.jsx
  src/components/support/Support.jsx
  src/data/support/Socials.jsx
Labels: Fix Changes, Sean, Support

#52 added title.js
  src/components/Title.jsx
  src/components/home/Involve.jsx
  src/components/home/Upcoming.jsx
  src/data/Title.js
Labels: Fix Changes, Sean, General

#49 implement board page
  src/app/board/page.js
  src/data/Title.js
  src/data/boardMembers.js
  tailwind.config.js
Labels: Ready to Review, Sean

#63 HaokunYang123/Hoverable
  src/app/gallery/page.js
  src/components/gallery/Hoverable.jsx
Labels: Fix Changes, Sean, Gallery

#69 Tabling
  src/app/involve/page.js
  src/components/involvement/Tabling.jsx
  src/data/involve/Tabling.js
Labels: Help

#70 Created landing component
  src/components/home/Landing.jsx
  tailwind.config.js
Labels: Ready to Review, Quin

#71 Implemented routng for gallery page
  src/app/gallery/[type]/page.js
Labels: Fix Changes, Sean, Gallery

#72 Title Shadow Fixed
  src/components/Title.jsx
  src/data/Title.js
  tailwind.config.js
Labels: Ready to Review, Sean

#73 404 page
  src/app/not-found.js
  src/components/Subtitle.jsx
Labels: Ready to Review, Quin

#74 added info to support page
  src/components/support/Support.jsx
Labels: Ready to Review, Quin

#82 Involvement
  src/app/involve/page.js
  src/components/involvement/Tabling.jsx
Labels: Ready to Review

#79 Implemented FAQs.jsx
  src/components/Item.jsx
  src/components/involvement/FAQs.jsx
  src/data/involve/Questions.js
Labels: Fix Changes, Sean

#78 implement support page
  src/components/support/Support.jsx
  src/data/Title.js
  tailwind.config.js
Labels: Ready to Review, Quin

#94 Haokun yang123/gallery home page
  src/app/gallery/page.js
  src/components/gallery/Hoverable.jsx
  src/data/gallery/QuarterlyEvents.js
Labels: Fix Changes, Sean, Gallery

#88 added about page
  src/app/about/page.js
  src/data/aboutPage.js
Labels: Ready to Review, Sean, About

#98 Implemented the pics into the board page
  src/data/board/Board.js
Labels: Ready to Review, Board

#97 Added mobile responsiveness for Upcoming Events
  src/components/home/Upcoming.jsx
  src/components/home/UpcomingCard.jsx
Labels: Ready to Review, Quin

#102 Fix Button
  src/components/Button.jsx
Labels: Ready to Review, Bug

#101 Centered Board
  src/app/board/page.js
Labels: Ready to Review, Quin, Board, Bug

#100 make subtitle smaller + centered
  src/components/Subtitle.jsx
Labels: Ready to Review, Quin

#107 final responsive title changes
  src/components/Footer.jsx
  src/components/Subtitle.jsx
  src/components/Title.jsx
  src/components/gallery/Hoverable.jsx
Labels: Ready to Review

#105 Added mobile responsiveness for Support + bug fix
  src/components/support/Support.jsx
Labels: Ready to Review, Fix Changes, Sean, Support, Bug

#108 Landing Responsive
  src/components/home/Landing.jsx
Labels: Fix Changes, Sean

#119 Navbar fix
  src/components/Navigation.jsx
Labels: Ready to Review

#118 Made the footer thicker and icon more space out
  src/components/Footer.jsx
Labels: Ready to Review, Sean, Bug

#109 jefren/mobile responsiveness for galler
  src/app/gallery/[type]/page.js
  src/app/gallery/page.js
Labels: Ready to Review, Gallery

#125 Adjusting mobile responsiveness on about page
  src/app/about/page.js
Labels: Fix Changes, Sean, About, Bug

#126 Centered board items
  src/app/board/page.js
Labels: Ready to Review, Quin, Bug

#124 Footer Responsive
  src/components/Footer.jsx
Labels: Ready to Review, Quin

#127 Removing background on FAQ to make blobs transparent
  src/app/involve/page.js
  src/components/involvement/FAQs.jsx
Labels: Ready to Review, Sean, Involvement, Bug

#130 added blobs and bg color also changed color to the right one
  src/app/gallery/[type]/page.js
  src/app/gallery/page.js
Labels: Ready to Review, Gallery
