Repository acm-ucr/h4b-website, pull requests merged in 2024-08, with the labels that each got.

#133 added calendar date header
  src/components/events/CustomHeader.jsx
Labels: Ready to Review

#131 footer icons hover animation + fix
  src/components/Footer.jsx
Labels: Ready to Review, Sean

#146 Adjust Mobile responsiveness for upcoming events
  src/components/home/UpcomingCard.jsx
Labels: Bug

#140 Social Icons and Events.jsx
  src/components/events/CalendarEvents.jsx
  src/components/events/CustomEvents.jsx
  src/components/support/Connect.jsx
  src/components/support/Support.jsx
  tailwind.config.js
Labels: Fix Changes, Sean

#148 mobile landing
  public/images/mobilelanding.webp
  src/components/home/Landing.jsx
Labels: Ready to Review, Sean

#150 Adding animation to board page
  src/app/board/page.js
  src/components/board/Board.jsx
Labels: Ready to Review, Quin, Board, Animation

#152 Events format change
  src/components/home/UpcomingCard.jsx
Labels: Bug

#134 Implemented Modal.jsx
  src/components/events/Modal.jsx
  tailwind.config.js
Labels: Ready to Review, Fix Changes, Quin, Events

#153 styled toolbar
  src/components/events/CustomToolbar.jsx
Labels: Ready to Review, Sean, Events

#156 Fixed FAQ click responsiveness
  src/components/involvement/FAQs.jsx
  src/components/involvement/Item.jsx
Labels: Ready to Review, Sean, Bug

#162 Jefren/QuarterPicAnimation
  src/app/gallery/[type]/page.js
  src/components/gallery/GalleryImage.jsx
Labels: Ready to Review, Sean, Gallery

#168 added animation for support page
  src/components/support/Support.jsx
Labels: Ready to Review, Support, Animation

#161 animated home page
  src/components/home/Involve.jsx
  src/components/home/Landing.jsx
  src/components/home/Upcoming.jsx
Labels: Ready to Review, Quin

#172 About Page Animation FIXESS
  src/app/about/page.js
  src/components/Subtitle.jsx
Labels: Fix Changes, Animation

#174 Updating board member years
  src/data/board/Board.js
Labels: Ready to Review, Board

#175 Nav Logo Change
  public/images/H4BNavLogo.webp
  src/components/Navigation.jsx
Labels: Ready to Review

#173 Adding Month to Calendar
  src/components/events/CalendarEvents.jsx
Labels: Fix Changes, Sean, Events

#171 Made Socials scale on hover
  src/components/support/Connect.jsx
Labels: Ready to Review, Quin, Animation

#170 Cleanup + Responsiveness Involve
  src/components/Picture.jsx
  src/components/involvement/AdditionalInfo.jsx
  src/components/involvement/Item.jsx
  src/components/involvement/Tabling.jsx
Labels: Ready to Review, Fix Changes, Sean, Involvement, Bug

#187 added blobs and color to calnedar
  src/app/events/page.js
Labels: Ready to Review, Events

#155 gallery main page animation
  src/app/gallery/page.js
  src/components/gallery/FoodTabling.jsx
  src/components/gallery/PastEvents.jsx
  src/components/gallery/QuarterlyEvents.jsx
Labels: Ready to Review, Quin

#178 Fixed about Pages
  public/images/spring/NewImg.webp
  src/app/about/page.js
  src/components/Picture.jsx
Labels: Ready to Review, Quin

#197 animated involvement
  src/app/involve/page.js
  src/components/involvement/AdditionalInfo.jsx
  src/components/involvement/FAQs.jsx
  src/components/involvement/Tabling.jsx
Labels: Ready to Review, Quin

#200 Fixed hydration error for events
  src/components/events/CalendarEvents.jsx
Labels: Ready to Review, Bug

#198 Added Extras section in gallery
  src/app/gallery/[type]/page.js
  src/app/gallery/page.js
  src/components/gallery/ExtraPhotos.jsx
Labels: Ready to Review, Fix Changes, Sean, Gallery

#202 Landing Mobile Icon Spacing
  src/components/home/Landing.jsx
Labels: Quin

#196 Updating shadow for mobile on involve page
  src/components/Title.jsx
  tailwind.config.js
Labels: Fix Changes, Sean, Involvement

#213 New Hover changes
  src/components/gallery/Hoverable.jsx
Labels: Ready to Review, Quin

#205 HoverTextFix
  src/components/gallery/Hoverable.jsx
Labels: Ready to Review, Quin

#212 fixed mobile responsiveness for button
  src/components/Button.jsx
Labels: Quin

#214 home page responsiveness
  src/components/home/Goal.jsx
  src/components/home/Involve.jsx
Labels: Ready to Review

#215 Google cal integration
  src/components/home/Upcoming.jsx
  src/components/home/UpcomingCard.jsx
Labels: Fix Changes, Sean
